services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        COUNTRY: CN
    image: nezha:dev
    container_name: nezha-dev
    ports:
      - ${NEZHA_PORT:-80}:18080
      - 5555:5555
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/dashboard/data
      # - ./resource:/dashboard/resource